### ISSUE TITLE
Abfahrtszeit auswählen

### ISSUE THREAD

**Issue by vainamov** [sunrisesdev/aboard#70]
Wir zeigen aktuell nur die erste Seite der Abfahrten einer Station, basierend auf der aktuellen Uhrzeit an. Wir sollten die Pagination des Endpunktes implementieren, damit man auch frühere bzw. spätere Fahrten auswählen kann. Außerdem wäre es gut, die Abfahrtszeit direkt eingeben zu können.

**Comment by NoelBank** [comment]
Idee 1:
- Man könnte per Infinity Scrolling weitere Einträge laden?

**Comment by vainamov** [comment]
> Man könnte per Infinity Scrolling weitere Einträge laden?
Zusätzlich über die Pull-To-Refresh Geste könnte man am oberen Ende der Liste vorherige Einträge laden.

Scroll-basiertes Laden hat nur das Problem, wenn die Anzahl der Einträge nicht für Overflow sorgt, kann man gar nicht scrollen. Wir brauchen also vermutlich eine Fallback-Lösung mit Click Handlern.
